### ISSUE TITLE
bridge data set is not accessible

### ISSUE THREAD

**Issue by ed2k** [facebookresearch/jps#4]
drop box returns 
`You don’t have access to this content.`

**Comment by yuandong-tian** [comment]
you can first use https://yuandong-tian.com/bridge_dataset.tar.gz. I will fix the link to provide an official one later.

**Comment by ed2k** [comment]
thanks for the response, seems the new link is returning 404.

**Comment by yuandong-tian** [comment]
Sorry for the issue. Now it should work. Please try again.

**Comment by yuandong-tian** [comment]
The official link is updated. Closing the issue.
